//
// Created by dzing on 26/02/2021.
//

#ifndef VISORV3_PXMATRIXPINDEFINITIONS_H
#define VISORV3_PXMATRIXPINDEFINITIONS_H

//PINS CONFIGURATION
#define PIN_INPUT_DIPSWITCH_1 35
#define PIN_INPUT_DIPSWITCH_2 34
#define PIN_INPUT_DIPSWITCH_3 39
#define PIN_INPUT_DIPSWITCH_4 36
#define PIN_INPUT_BUTTON 24

#define PIN_OUTPUT_WS 32
#define PIN_OUTPUT_USB_DPLUS 25
#define PIN_OUTPUT_USB_DMINUS 26
#define PIN_DAC_USB_DPLUS DAC1
#define PIN_DAC_USB_DMINUS DAC2

#define PIN_OUTPUT_MAX_MOSI 27
#define PIN_OUTPUT_MAX_CLK 12
#define PIN_OUTPUT_MAX_CS 13

#define PIN_SD_CLK 14
#define PIN_SD_D0 2
#define PIN_SD_CMD 15

#define PIN_OUTPUT_PX_MOSI 23
#define PIN_OUTPUT_PX_CLK 18
#define PIN_OUTPUT_PX_STROBO 5
#define PIN_OUTPUT_PX_REGLATCH PIN_OUTPUT_PX_STROBO
#define PIN_OUTPUT_PX_OE 19

#define PIN_EMPTY_1 17
#define PIN_EMPTY_2 16
#define PIN_EMPTY_3 4

#define PIN_SDA 21
#define PIN_SCL 22
//Set to 255 if no reset pin
#define PIN_OLED_RESET 255

#define PIN_DHT22TEMP 33

#define I2C_OLED_ADDRESS 0x0
#define I2C_CURRENTMETER_ADDRESS 0x0

#define PIN_REG_FIRST 0
#define PIN_BUZZER PIN_REG_FIRST
#define PIN_REG_SECOND 1
#define PIN_REG_THIRD 2
#define PIN_REG_FOURTH 3

#endif //VISORV3_PXMATRIXPINDEFINITIONS_H
